name: constat_tunisie
description: "Application mobile pour la gestion des constats amiables d'accidents automobiles en Tunisie."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  firebase_messaging: ^14.6.7
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5

  # Autres dépendances
  provider: ^6.0.5
  go_router: ^10.1.2
  shared_preferences: ^2.2.1
  flutter_native_splash: ^2.3.10  # Pour configurer le splash screen natif
  lottie: ^3.0.0  # Pour les animations (optionnel)
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  logger: ^1.4.0
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.2
  url_launcher: ^6.1.12
  connectivity_plus: ^4.0.2
  flutter_launcher_icons: ^0.13.1
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.2.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  pdf: ^3.10.4
  share_plus: ^7.1.0
  photo_view: ^0.14.0
  flutter_signature_pad: ^3.0.1
  printing: ^5.11.0
  geocoding: ^2.1.0
  intl: ^0.18.1
  google_mlkit_text_recognition: ^0.10.0




  # Commenté temporairement pour résoudre les problèmes de compilation
  # flutter_local_notifications: ^14.1.1
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    # Ajoutez le répertoire des polices si nécessaire
    - assets/fonts/

  # Correction de l'indentation et de la structure pour les polices
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
